### ISSUE TITLE
BUG :: SimpleChoiceList doesn't exist

### ISSUE THREAD

**Issue by gdbrown** [gdbots/pbjx-bundle-php#4]
In Class `Gdbots\Bundle\PbjxBundle\Form\Type\KeyValueType` it uses `use Symfony\Component\Form\Extension\Core\ChoiceList\SimpleChoiceList;` which doesn't exist.

**Comment by excelwebzone** [comment]
> Note: I have disabled the inline `constraints` option.. seems to not be supported anymore.
